### ISSUE TITLE
Cannot run experiments

### ISSUE THREAD

**Issue by Smu-Tan** [cog-isa/forger#1]
**Hi, Im trying to run train_simple_set.py, however I encountered errors below. And I also tried to run train_treechop, but the program seems not running according to GPU memory usage. You mentioned about expert data should be put in the `demonstrations folder`, is that mean putting the MineRL demonstration data folder under the `demonstration folder `without any processing? Thank you!** 

`(MineRL) F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master>python train_simple_set.py --config simple_set_config.yaml
2021-07-13 20:35:52.820815: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to
use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Building model
Building model
Building model
Building model`
  9%|██████████▊                                                                                                              | 8917/100000 [00:00<00:05, 18071.75it/s]d
emo data added to buff
 10%|████████████                                                                                                             | 9991/100000 [00:00<00:05, 17888.77it/s]
`all data set 0
Pre-training ...
Q-nn_update tracing
Building model`
`Traceback (most recent call last):
  File "train_simple_set.py", line 76, in <module>
    run_pipeline(params.config)
  File "train_simple_set.py", line 65, in run_pipeline
    agent.pre_train(**config['pretrain'])
  File "F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\agent.py", line 129, in pre_train
    self.update(steps)
  File "F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\agent.py", line 137, in update
    priorities = self.q_network_update(gamma=self.gamma, **batch)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\eager\function.py", line 3735, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
`TypeError: in user code:

    F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\agent.py:170 q_network_update  *
        q_value = take_vector_elements(q_value, action)
    F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\utils\tf_util.py:37 take_vector_elements  *
        return tf.gather_nd(vectors, tf.stack([tf.range(tf.shape(vectors)[0]), indices], axis=1))
    F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\ops\array_ops.py:1389 stack
        return gen_array_ops.pack(values, axis=axis, name=name)
    F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\ops\gen_array_ops.py:6476 pack
        "Pack", values=values, axis=axis, name=name)
    F:\anaconda\envs\MineRL\lib\site-packages\tensorflow\python\framework\op_def_library.py:442 _apply_op_helper
        raise TypeError("%s that don't all match." % prefix)

    TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int32, int64] that don't all match.`

**Comment by Tviskaron** [comment]
@Smu-Tan Hi! I can't reproduce that error but I suppose the problem in versions of packages. Please try to reinstall with the updated [requirements.txt](https://github.com/cog-isa/forger/blob/master/requirements.txt) file.  
Also, you can use a prebuilt docker image with all needed dependencies and demonstrations: 
```docker pull tviskaron/forger:latest```

**Comment by Smu-Tan** [comment]
> @Smu-Tan Hi! I can't reproduce that error but I suppose the problem in versions of packages. Please try to reinstall with the updated [requirements.txt](https://github.com/cog-isa/forger/blob/master/requirements.txt) file.
> Also, you can use a prebuilt docker image with all needed dependencies and demonstrations:
> `docker pull tviskaron/forger:latest`

Hi, @Tviskaron , unfortunately, I tried to use python3.6 and all the packages whose versions are aligned with versions in the requirement.txt file, however, there're still tons of bugs.  However, I successfully repaired all the bugs in `simple_set experiment` and `treechop experiment`, now those experiments can be successfully run, even though for the later one, the program will be crashed if I set the buffer size beyond 6000, but I guess that probably because of the limitation of my RAM(16GB).

But I still cannot run the `train minerl experiment` , and the problem now I have is: when I extract `chain`  and `final chain` in `train_minerl.py`, the data structure seems wrong somehow. And I tried to fixed some bugs but the `chain result ` and `final chain result ` I got seems wrong. 

![9028b1b27eb77d26dd9abc18d5c540d](https://user-images.githubusercontent.com/79228128/128692348-775bcdda-f6f6-430f-b386-d8a772d2ab16.png)
![b505fe348fc43024d81a57d6ffa0592](https://user-images.githubusercontent.com/79228128/128692361-281e0509-17ba-4174-bff5-10e666dee35e.png)

First, all the values of actions in  `chain`  and `final chain`  are `none`.  What's more, the data structure in `final chain` seems wrong, because those `none` strings should be `int(0)` according to the `string_to_action_dict function`.
![052e0d20cc38b5a659192f1aeb3043b](https://user-images.githubusercontent.com/79228128/128692691-81b8d01c-602d-453d-b66b-f8d4384dda95.png)

I would appreciate it if you could give me some tips or suggestions.

**Comment by Smu-Tan** [comment]
> @Smu-Tan After some investigation, I think what MineRL team has changed the demonstrations format... Please try to run code with the old file format, here is a [link](https://drive.google.com/drive/folders/1O1hCBytpMCTELRdkbwsxj1pBfdzdleuY?usp=sharing).

Hi, thanks for providing help! However when I trying to run the program `train_minerl`, I still got many bugs, I think this is because of the MineRL package issue, e.g: when using sarsd_iter function, it mentioned 'Your data is OUT-OF-DATE, please download the newest dataset'. I do use the `minerl==0.2.9`, therefore, I changed the data structure from the newest dataset to the old version one, and now I can get the correct chain! 

But things went wrong when I run the `pretrain function in train_minerl`. specifically, in the ItemAgent's pretrain function of the ItemAgent.py, see the figure below:
![image](https://user-images.githubusercontent.com/79228128/132143702-00662e4a-b643-47e2-b676-290ee3c2081d.png)


It mentioned `'DummyDataLoader' object has no attribute 'batch_iter'`(see error below), which I think line 366 and 372 should be `node.pov_agent.agent.add_demo(data.data, 0, fixed_reward=0)`? Coz it will use sarsd_iter function which the `DummyDataLoader Class` has. 

![image](https://user-images.githubusercontent.com/79228128/132143667-861f5554-807e-4c46-8d41-c41e43229f49.png)


Hence, I changed it to  `node.pov_agent.agent.add_demo(data.data, 0, fixed_reward=0)`, see the new code below. 
![image](https://user-images.githubusercontent.com/79228128/132143829-80e6fd8e-4cfd-4718-9c85-cd5c8486c7d0.png)


however there's a new error on line 19: `node.pov_agent.agent.pre_train(train_config['pretrain']['steps']) #errors in this step` . It is caused when running the sample function in the replay_buffer. the whole error is: 
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-33-7917c89f5334> in <module>
     17 
     18     print(f'Pre-training {node.name} agent')
---> 19     node.pov_agent.agent.pre_train(train_config['pretrain']['steps']) #errors in this step
     20     #node.pov_agent.save_agent()
     21     #self.pov_agents[node.name] = node.pov_agent

F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\agent.py in pre_train(self, steps)
    130         print('Pre-training ...')
    131         self.target_update()
--> 132         self.update(steps)
    133         self.save(os.path.join(self.save_dir, "pre_trained_model.ckpt"))
    134         print('All pre-train finish.')

F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\agent.py in update(self, steps)
    136     def update(self, steps):
    137         start_time = timeit.default_timer()
--> 138         for batch in self.sampler(steps):
    139             indexes = batch.pop('indexes')
    140             priorities = self.q_network_update(gamma=self.gamma, **batch)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\ops\iterator_ops.py in __next__(self)
    759   def __next__(self):
    760     try:
--> 761       return self._next_internal()
    762     except errors.OutOfRangeError:
    763       raise StopIteration

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\ops\iterator_ops.py in _next_internal(self)
    745           self._iterator_resource,
    746           output_types=self._flat_output_types,
--> 747           output_shapes=self._flat_output_shapes)
    748 
    749       try:

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\gen_dataset_ops.py in iterator_get_next(iterator, output_types, output_shapes, name)
   2725       return _result
   2726     except _core._NotOkStatusException as e:
-> 2727       _ops.raise_from_not_ok_status(e, name)
   2728     except _core._FallbackException:
   2729       pass

~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py in raise_from_not_ok_status(e, name)
   6939   message = e.message + (" name: " + name if name is not None else "")
   6940   # pylint: disable=protected-access
-> 6941   six.raise_from(core._status_to_exception(e.code, message), None)
   6942   # pylint: enable=protected-access
   6943 

F:\anaconda\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
Traceback (most recent call last):

  File "C:\Users\Tan\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\script_ops.py", line 249, in __call__
    ret = func(*args)

  File "C:\Users\Tan\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\autograph\impl\api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Tan\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 892, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\agent.py", line 155, in sample_generator
    yield self.replay_buff.sample(self.batch_size)

  File "F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\replay_buff.py", line 244, in sample
    samples = self.demo_buff.sample(demo_n, beta)

  File "F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\replay_buff.py", line 168, in sample
    encoded_sample = self._encode_sample(idxes)

  File "F:\PythonJupyterStudy\RL_Minecraft\forger-master\forger-master\ForgER\replay_buff.py", line 63, in _encode_sample
    batch[key] = np.array(value, dtype=self.env_dict[key]['dtype'])

TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]
